apiVersion: apps/v1
kind: Deployment  
metadata:
  name: backend-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: backend-app 
    spec:
      containers:
      - name: backend-app 
        image: piyu5233/angular-test:backend
        ports:
        - name: springboot-tomcat
          containerPort: 8085
          protocol: TCP 
