apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-access-binding
  namespace: default
subjects:
- kind: User
  name: system:node:ip-172-31-31-240.ec2.internal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-access
  apiGroup: rbac.authorization.k8s.io
